apiVersion: 1

datasources:
  - name: LOGIC API
    uid: logic-infinity
    type: yesoreyeram-infinity-datasource
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      allowed_hosts:
        - ${LOGIC_API_URL}
        - http://localhost:4000
        - http://api:4000
